---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: var-volume
  namespace: jenkins
  labels:
    type: local
    app: jenkins
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/jenkins"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: var-claim
  namespace: jenkins
  labels:
    app: jenkins
spec:
  volumeName: var-volume
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: partlab/ubuntu-jenkins:latest
        ports:
        - containerPort: 8080
          name: portjenkins
          protocol: TCP
        volumeMounts:
        - mountPath: /var/jenkins
          name: jenkins-pv1
      volumes:
      - name: jenkins-pv1
        persistentVolumeClaim:
          claimName: var-claim
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30088
    protocol: TCP
    name: webuiport
  selector:
   app: jenkins
